server:
  port: 8080
#  ssl:
#    key-store-type: pkcs12
#    key-alias: local
#    enabled: true
#    key-store:
#    key-store-password:

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_ID}
    password: ${DB_PW}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql : true
        default_batch_fetch_size: 1000 # where in ()

    show-sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.type: TRACE

file:
  upload:
    path:

