server:
  port: 8080
#  ssl:
#    key-store:
#    key-store-password:
#    key-store-type: pkcs12
#    key-alias: tomcat
#    enabled: true

spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        default_batch_fetch_size: 1000 # where in ()

    show-sql: false
    open-in-view: false

logging:
  level:
    org.hibernate.type: INFO

