server:
  port: 8080
#  ssl:
#    key-store-type: pkcs12
#    key-alias: local
#    enabled: true
#    key-store:
#    key-store-password:

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: ${DB_URL}
    username: ${DB_ID}
    password: ${DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql : true
        default_batch_fetch_size: 1000 # where in ()

    show-sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.type: trace

file:
  upload:
    path:

jwt:
  secret: ${token.secret}
  access-token-expiration-time: ${token.access-token-expiration-time}
  refresh-token-expiration-time: ${token.refresh-token-expiration-time}

  mail:
    host: smtp.naver.com #smtp
    port: 465
    username: ${email.id}
    password: ${email.pw}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          #            required: true
          auth: true
          #          connectiontimeout: 5000
          #          timeout: 5000
          #          writetimeout: 5000
          ssl:
            trust: smtp.naver.com
            enable: true